/** The 3 hand-drawn whale-girl frames. */
export const WHALE_GIRL_FRAMES = [
    {
        name: 'standard',
        rows: [
            '........................................',
            '..............L.........................',
            '.............LLL........................',
            '..............L.........................',
            '........................................',
            '..........DDDDDDDD......................',
            '.........DBBLLBBBBD.....................',
            '........DBBBBBBBBBBD....................',
            '........DBSSSSSSSSBD....................',
            '........DBSSSSSSSSBD....................',
            '........DBSDDSSDDSBD....................',
            '........DBSDDSSDDSBD....................',
            '........DBPSSSSSSPBD....................',
            '.........DSSSDDSSSSD..D.................',
            '..........DDDDDDDD...DBD.....D..........',
            '.........DWWBBBBWWD..DBBD...DBD.........',
            '........DWWWWWWWWWD..DBBBD.DDBBD........',
            '.......DSWWWWWWWWSD..DBBBBDDBBBBD.......',
            '.......DSWWWWWWWWSD...DBBBBBBBBD........',
            '........DWWWWWWWWWD...DBBBBBBBD.........',
            '.......DWWWWWWWWWWWDBBDBBBBBDD..........',
            '......DWWWWWWWLLLLWWD...................',
            '......DDDDDDDDDDDDDDD...................',
            '........SS......SS......................',
            '........DD......DD......................',
        ],
    },
    {
        name: 'blink',
        rows: [
            '........................................',
            '..............L.........................',
            '.............LLL........................',
            '..............L.........................',
            '........................................',
            '..........DDDDDDDD......................',
            '.........DBBLLBBBBD.....................',
            '........DBBBBBBBBBBD....................',
            '........DBSSSSSSSSBD....................',
            '........DBSSSSSSSSBD....................',
            '........DBSSSSSSSSBD....................',
            '........DBSDDSSDDSBD....................',
            '........DBPSSSSSSPBD....................',
            '.........DSSSDDSSSSD..D.................',
            '..........DDDDDDDD...DBD.....D..........',
            '.........DWWBBBBWWD..DBBD...DBD.........',
            '........DWWWWWWWWWD..DBBBD.DDBBD........',
            '.......DSWWWWWWWWSD..DBBBBDDBBBBD.......',
            '.......DSWWWWWWWWSD...DBBBBBBBBD........',
            '........DWWWWWWWWWD...DBBBBBBBD.........',
            '.......DWWWWWWWWWWWDBBDBBBBBDD..........',
            '......DWWWWWWWLLLLWWD...................',
            '......DDDDDDDDDDDDDDD...................',
            '........SS......SS......................',
            '........DD......DD......................',
        ],
    },
    {
        name: 'spout',
        rows: [
            '............L...L.......................',
            '............LLLLL.......................',
            '.............LLL........................',
            '..............L.........................',
            '..............L.........................',
            '..........DDDDDDDD......................',
            '.........DBBLLBBBBD.....................',
            '........DBBBBBBBBBBD....................',
            '........DBSSSSSSSSBD....................',
            '........DBSSSSSSSSBD....................',
            '........DBSDDSSDDSBD....................',
            '........DBSDDSSDDSBD....................',
            '........DBPSSSSSSPBD....................',
            '.........DSSSDDSSSSD..D.................',
            '..........DDDDDDDD...DBD.....D..........',
            '.........DWWBBBBWWD..DBBD...DBD.........',
            '........DWWWWWWWWWD..DBBBD.DDBBD........',
            '.......DSWWWWWWWWSD..DBBBBDDBBBBD.......',
            '.......DSWWWWWWWWSD...DBBBBBBBBD........',
            '........DWWWWWWWWWD...DBBBBBBBD.........',
            '.......DWWWWWWWWWWWDBBDBBBBBDD..........',
            '......DWWWWWWWLLLLWWD...................',
            '......DDDDDDDDDDDDDDD...................',
            '........SS......SS......................',
            '........DD......DD......................',
        ],
    },
];
/** Startup sequence (~1.8s), ending on the standard pose. */
export const WHALE_GIRL_OPENING_SEQUENCE = [
    { frame: 0, ms: 400 }, // standard
    { frame: 1, ms: 250 }, // blink
    { frame: 0, ms: 300 }, // standard
    { frame: 2, ms: 500 }, // spout
    { frame: 0, ms: 300 }, // standard
];
